export const TYPES = {
  READ_DATA: 'READ_DATA',
  ADD_TO: 'ADD_TO',
  MOVE_TO: 'MOVE_TO',
  CANCEL: 'CANCEL',
  SET_ERROR: 'SET_ERROR',
  FILTER_BY_DATES: 'FILTER_BY_DATES',
  UNLOAD_LAYOUT: 'UNLOAD_LAYOUT',
};
